### ISSUE TITLE
menu entry Maintenance Windows to Reports | Configuration Reports

### ISSUE THREAD

**Issue by fredhohenstein** [PRTG/PRTGScheduler#14]
The menu entry Maintenance Windowsto Reports | Configuration Reports dows not appaer

**Comment by stephanlinke** [comment]
Sorry for the delay, I somehow missed that. I assume that you're running 17.4 or newer (i.e. the new GUI)? Then please check https://github.com/PRTG/PRTGScheduler/issues/12 :)
