### ISSUE TITLE
Next Start Not Correct

### ISSUE THREAD

**Issue by Manimi-Chart** [PRTG/PRTGScheduler#16]
I have the comments of my sensor setup as follows:
![2018-08-23 11_36_35-sla prime _ sensor details _ prtg network monitor](https://user-images.githubusercontent.com/32491745/44542086-1540b680-a6c9-11e8-9343-3092ba64656a.png)
They are two separate maintenance window days, back to back at the same time of day.

However the report shows as follows:
![2018-08-23 11_37_27-configuration report_ user accounts and user groups _ prtg network monitor](https://user-images.githubusercontent.com/32491745/44542164-415c3780-a6c9-11e8-9b72-c9fdf90a876b.png)
It shows both days as listed.  However, the next start day at the top shows the second day, not the first.  

Does this mean that the first day won't go into maintenance mode because the second one is on-deck? 
How do I get the first day to be the Next Start and not the second?

**Comment by stephanlinke** [comment]
Usually, they should be indeed sorted by their actual date order. Did you configure the timezone (within the application config) and is the user set to UTC?

**Comment by Manimi-Chart** [comment]
The Application Config default timezone is set to "America/Denver". And the prtgscheduler user timezone is set to UTC.

**Comment by stephanlinke** [comment]
Alright, good. Then I‘ll need the output of the powershell script with debug being enabled. I‘m currently on vacation, so I can‘t recreate the issue :/

**Comment by Manimi-Chart** [comment]
Here is the debug results from the PowerShell script.   Have a great vacation! 

[PRTG-Scheduler Debug Output.txt](https://github.com/PRTG/PRTGScheduler/files/2349867/PRTG-Scheduler.Debug.Output.txt)

**Comment by stephanlinke** [comment]
It‘s seemingly a bug, since the maintenance window gets calculated wrong and is not considered sonehow. I‘ll check this next Wednesday when I get back to work :)

**Comment by stephanlinke** [comment]
@Manimi-Chart I seemingly found the issue in application\models\Maintenance_model.php, line 96. It said _k**r**sort($maintenanceWindows);_ instead of _ksort($maintenanceWindows)_; 

This caused the array to be sorted the wrong way (inverse, namely). This is the only change that needs to be done here. I'll commit the changes as well. Thanks for pointing that one out!

**Comment by Manimi-Chart** [comment]
I can confirm that this did fix the issue.  Thank you!

**Comment by mafer0410** [comment]
hello, where is the maintenance status configured?
